version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    mem_limit: 300m
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=config.settings.${MODE}
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    mem_limit: 200m
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx-${MODE}.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./media:/code/media
      - /etc/letsencrypt/live/gamari-devs.com/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/gamari-devs.com/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - web
    mem_limit: 100m
volumes:
  db_data:
